### ISSUE TITLE
argopy.errors.DataNotFound: 'All URLs returned DataNotFound !'

### ISSUE THREAD

**Issue by charlyf66** [euroargodev/argopy#422]
Hi,

Thanks for the great work.
I tried to reinstall argopy on a computer but I have an error.

Basically I do : 

$ python -m venv ~/venvs/a
$ source ~/venvs/a/bin/activate
$ pip install argopy

It works and all dependencies seem satisfied.
But when I try to fetch I got the error :

?: Queued | w: Downloading netcdf from the erddap | p: Formatting xarray dataset | c: Callback | f: Failed or No Data | s: Success
[????]
Processing data chunks (0% processed) ...
Traceback (most recent call last):
  File "/home/xxxxx/DATA_MED/datasets/ARGO/get_argo.py", line 72, in <module>
    f = f.region(box).load()
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxxx/venvs/a/lib/python3.12/site-packages/argopy/fetchers.py", line 792, in load
    self._data = self.to_xarray(**kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxxx/venvs/a/lib/python3.12/site-packages/argopy/fetchers.py", line 616, in to_xarray
    xds = self.fetcher.to_xarray(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxxx/venvs/a/lib/python3.12/site-packages/argopy/data_fetchers/erddap_data.py", line 804, in to_xarray
    results = self.fs.open_mfdataset(URI, **opts)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxxx/venvs/a/lib/python3.12/site-packages/argopy/stores/filesystems.py", line 1141, in open_mfdataset
    return self._open_mfdataset_from_erddap(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxxx/venvs/a/lib/python3.12/site-packages/argopy/stores/filesystems.py", line 1041, in _open_mfdataset_from_erddap
    raise results
argopy.errors.DataNotFound: 'All URLs returned DataNotFound !'

Any idea ?? Here is my pip freeze for this environment : 

aiohappyeyeballs==2.4.4
aiohttp==3.11.10
aiosignal==1.3.2
anyio==4.7.0
argopy==1.0.0
attrs==24.3.0
certifi==2024.12.14
cftime==1.6.4.post1
charset-normalizer==3.4.0
contourpy==1.3.1
cycler==0.12.1
decorator==5.1.1
erddapy==2.2.3
fonttools==4.55.3
frozenlist==1.5.0
fsspec==2023.10.0
h11==0.14.0
httpcore==1.0.7
httpx==0.28.1
idna==3.10
kiwisolver==1.4.7
matplotlib==3.10.0
multidict==6.1.0
netCDF4==1.7.2
numpy==1.26.4
packaging==24.2
pandas==2.2.3
pillow==11.0.0
propcache==0.2.1
pyparsing==3.2.0
python-dateutil==2.9.0.post0
pytz==2024.2
requests==2.32.3
scipy==1.14.1
six==1.17.0
sniffio==1.3.1
toolz==1.0.0
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.2.3
xarray==2024.2.0
yarl==1.18.3

Thanks !

**Comment by charlyf66** [comment]
Sorry I was able to make it work with some tuning, seems to be a problem on my side
