### ISSUE TITLE
"Try it" example on Binder is broken; a fresh installation is broken in the same way

### ISSUE THREAD

**Issue by jpivarski** [euroargodev/argopy#58]
It looks like a broken link; maybe a URL has changed? (Or since this is built from master, maybe a URL hasn't been changed yet?)

![image](https://user-images.githubusercontent.com/1852447/95633185-c2631e00-0a4c-11eb-9f30-c39cc12c5f08.png)

...

ClientResponseError: 500, message='500', url=URL('https://www.ifremer.fr/erddap/tabledap/ArgoFloats.nc?data_mode,latitude,longitude,position_qc,time,time_qc,direction,platform_number,cycle_number,config_mission_number,vertical_sampling_scheme,pres,temp,psal,pres_qc,temp_qc,psal_qc,pres_adjusted,temp_adjusted,psal_adjusted,pres_adjusted_qc,temp_adjusted_qc,psal_adjusted_qc,pres_adjusted_error,temp_adjusted_error,psal_adjusted_error&longitude%3E=-75&longitude%3C=-45&latitude%3E=20&latitude%3C=30&pres%3E=0&pres%3C=100&time%3E=1293840000.0&time%3C=1296518400.0&distinct()&orderBy(%22time,pres%22)')

**Comment by jpivarski** [comment]
I also tried installing from conda. After working around issue #59, I see the same error as above when I try to `.to_dataframe()` or `.to_xarray()` (which I suspect initiates the download that fails due to a wrong URL).

```python
>>> from argopy import DataFetcher as ArgoDataFetcher
/home/jpivarski/miniconda3/lib/python3.8/site-packages/argopy/plotters.py:33: UserWarning: argopy requires cartopy installed for full map plotting functionality
  warnings.warn("argopy requires cartopy installed for full map plotting functionality")
/home/jpivarski/miniconda3/lib/python3.8/site-packages/argopy/plotters.py:41: UserWarning: argopy requires seaborn installed for full plotting functionality
  warnings.warn("argopy requires seaborn installed for full plotting functionality")
>>> data = ArgoDataFetcher().region([-75, -45, 20, 30, 0, 100, '2011', '2012'])
```

So far, so good, but then both `data.to_dataframe()` or `data.to_xarray()` cause

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/argopy/fetchers.py", line 230, in to_dataframe
    return self.to_xarray(**kwargs).to_dataframe()
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/argopy/fetchers.py", line 222, in to_xarray
    xds = self.fetcher.to_xarray(**kwargs)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/argopy/data_fetchers/erddap_data.py", line 321, in to_xarray
    ds = self.fs.open_dataset(self.url)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/argopy/stores/fsspec_wrappers.py", line 253, in open_dataset
    ds = xr.open_dataset(of, **kwargs)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/xarray/backends/api.py", line 536, in open_dataset
    engine = _get_engine_from_magic_number(filename_or_obj)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/xarray/backends/api.py", line 121, in _get_engine_from_magic_number
    magic_number = filename_or_obj.read(8)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/fsspec/implementations/http.py", line 325, in read
    self._fetch_all()
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/fsspec/asyn.py", line 100, in wrapper
    return maybe_sync(func, self, *args, **kwargs)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/fsspec/asyn.py", line 80, in maybe_sync
    return sync(loop, func, *args, **kwargs)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/fsspec/asyn.py", line 51, in sync
    raise exc.with_traceback(tb)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/fsspec/asyn.py", line 35, in f
    result[0] = await future
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/fsspec/implementations/http.py", line 342, in async_fetch_all
    r.raise_for_status()
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 941, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='500', url=URL('https://www.ifremer.fr/erddap/tabledap/ArgoFloats.nc?data_mode,latitude,longitude,position_qc,time,time_qc,direction,platform_number,cycle_number,pres,temp,psal,pres_qc,temp_qc,psal_qc,pres_adjusted,temp_adjusted,psal_adjusted,pres_adjusted_qc,temp_adjusted_qc,psal_adjusted_qc,pres_adjusted_error,temp_adjusted_error,psal_adjusted_error&longitude%3E=-75&longitude%3C=-45&latitude%3E=20&latitude%3C=30&pres%3E=0&pres%3C=100&time%3E=1293840000.0&time%3C=1325376000.0&distinct()&orderBy(%22time,pres%22)')
```

I just looked up HTTP code 500. It isn't "not found" but "internal error." Maybe argopy itself is fine, but the server is down at the moment I'm testing it. I'll try again later, and if it all starts working, I'll just close this issue.

**Comment by quai20** [comment]
Hi @jpivarski 
Yes error 500 comes from the Erddap server, which can be touchy (sometimes, just relaunch the request is enough). I just tried the "try it" example on my machine and it works perfect.
![Capture du 2020-10-12 09-43-19](https://user-images.githubusercontent.com/17851004/95719088-9f648400-0c6f-11eb-8e3f-bb80cc29d6da.png)

**Comment by gmaze** [comment]
Note that:
- You can check on live status of web API used by argopy at: https://argopy.statuspage.io/
- And, we're working on a more informative user experience at #36

**Comment by jpivarski** [comment]
Nice! It is working now. The statuspage doesn't report an error on the day I tried it, though.

**Comment by gmaze** [comment]
> Nice! It is working now. The statuspage doesn't report an error on the day I tried it, though.

yes, this is possible if the down time falls in between 2 monitoring tests, which are separated by 5 to 10 minutes approximately, not frequent enough sometimes
