### ISSUE TITLE
Missing dependency: aiohttp is required

### ISSUE THREAD

**Issue by jpivarski** [euroargodev/argopy#59]
Following the [usage documentation](https://argopy.readthedocs.io/en/latest/usage.html),

```python
>>> from argopy import DataFetcher as ArgoDataFetcher
/home/jpivarski/miniconda3/lib/python3.8/site-packages/argopy/plotters.py:33:
 UserWarning: argopy requires cartopy installed for full map plotting functionality
  warnings.warn("argopy requires cartopy installed for full map plotting functionality")
/home/jpivarski/miniconda3/lib/python3.8/site-packages/argopy/plotters.py:41:
 UserWarning: argopy requires seaborn installed for full plotting functionality
  warnings.warn("argopy requires seaborn installed for full plotting functionality")

>>> data = ArgoDataFetcher().region([-75, -45, 20, 30, 0, 100, '2011', '2012'])
```

#### Expected Output

No error.  `:)`

#### Problem Description

The first traceback is:

```
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/fsspec/registry.py", line 186, in get_filesystem_class
    register_implementation(protocol, _import_class(bit["class"]))
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/fsspec/registry.py", line 201, in _import_class
    mod = importlib.import_module(mod)
  File "/home/jpivarski/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/fsspec/implementations/http.py", line 3, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
```

but then the exception chained to:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/argopy/fetchers.py", line 195, in region
    self.fetcher = self.Fetchers['region'](box=box, **self.fetcher_options)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/argopy/data_fetchers/erddap_data.py", line 85, in __init__
    self.fs = httpstore(cache=cache, cachedir=cachedir, timeout=120)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/argopy/stores/fsspec_wrappers.py", line 33, in __init__
    self.fs = fsspec.filesystem(self.protocol, **kw)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/fsspec/registry.py", line 218, in filesystem
    cls = get_filesystem_class(protocol)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/fsspec/registry.py", line 188, in get_filesystem_class
    raise ImportError(bit["err"]) from e
ImportError: HTTPFileSystem requires "requests" to be installed
```

which makes it look like "requests" is not installed. Actually, I do have "requests." What I didn't have was "aiohttp." This library is not included in the [list of dependencies](https://argopy.readthedocs.io/en/latest/install.html), nor was it automatically installed when I installed `argopy` from conda. It needs to go in a requirements list. I don't know whether it's correctly set up for pip; I only tested installation through conda. It's also possible that it's one of your dependencies that's not listing its dependencies.

With "aiohttp" installed, I can now run the above code and get a `data` object. (I haven't tried anything beyond that, yet.)

#### Versions

```python
>>> import argopy
>>> argopy.__version__
'0.1.6'
```

**Comment by gmaze** [comment]
Hi @jpivarski 
thanks for reporting this issue
aiohttp is now a dependency of fsspec, so I think this should be on them to fix this
but, in the mean time, we will add aiohttp to our own requirements to avoid this
g
